spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: git@github.com:Andrewp52/configs.git
          force-pull: true
        default-label: master

server:
  port: 8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
